language: rust
sudo: false
addons:
  apt:
    packages:
    - libgpgme11-dev
rust:
- stable
- beta
- nightly
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo '<meta http-equiv=refresh content=0;url=gpgme/index.html>' > target/doc/index.html &&
  pip install --user ghp-import &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: vaFY3OT9u3OhRmI7HQvC9ycfi9Ug0jaj1e+Ux9IWyOAie1Liq5dSOR2ngIwRJQeYQE4AJUfS87ZtsyYhnvQsDzmq5+CF7dO497LY03g61MZ7uHLB5wxd3zonj0kV1enVnpulqxlLxEgFXLH52hjZBqaMQD4aVVoF85ssW+WIZUowPIODwwfQp3j3/HruFnDbWLc4+gvPBKaczacihShrp1qimqkIfD/XBaKFgXgYCruJ8HXHLCKKNaX0DOsngvgjq36evJFlwj6sOz3eTa5Z3D9Z3S0hnwSUVySaCRPKpP1XXtvjP34vd5dUEyi8OzR2Yi6QzuHGW7/arJRqB/v/t7XnGeBWTIFyWZIP2h1Yr7Zi/Kp8Mi3F7WTxCK0EzmRFo10/7wL3HIcxM+/UF39tuRKC5NMC0DuXIEB5Ozdoq/N9K2RDpXpAfSEiRk5pBl0aPqfJUrIGWn8uBJp5XhHCxHn/wqN9CIs9wRY6XzpN/f3QKGyeA4fuzEmM//HM3dgZBS9raGAXlY0lky9N23TmRehHq9kLrGW0zeOEud98rbDYAlst7qcg2qQNkz/08UAPgt4L+kfKeFcS9DsUwlyrWYNJBPpQmxpeurvsyNFuclZhk3IHWuNHW69tRnHzdPlWts7u0K7DlNbwAQe/7driKbeKucT/Ms48B1i8x6GBk0k=
